remote_theme: sighingnow/jekyll-gitbook
title: Another's Homepage
description: Interesting thoughts share with the world

permalink: /:categories/:year-:month-:day-:title

syntax_highlighter_style: pastie
toc:
    enabled: true
    h_min: 2
    h_max: 3
